=begin
#mimepost

#MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 0.1.0
Contact: support@mimepost.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.18

=end

require 'spec_helper'
require 'json'

# Unit tests for Mimepost::StatsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatsApi' do
  before do
    # run before each test
    @instance = Mimepost::StatsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatsApi' do
    it 'should create an instance of StatsApi' do
      expect(@instance).to be_instance_of(Mimepost::StatsApi)
    end
  end

  # unit tests for emaillogs_get
  # Get the logs of a particular date
  # @param start_date Start Date in yyyymmdd format example 20190801
  # @param end_date End Date in yyyymmdd format example 20190803
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status 
  # @option opts [String] :to 
  # @option opts [Integer] :page 
  # @option opts [Integer] :limit 
  # @return [ApiResponseEmaillogs]
  describe 'emaillogs_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for stats_get
  # Get the summary of stats for a range of dates
  # @param start_date Start Date in yyyymmdd format example 20190801
  # @param end_date End Date in yyyymmdd format example 20190803
  # @param [Hash] opts the optional parameters
  # @return [ApiResponseStats]
  describe 'stats_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
