=begin
#mimepost

#MimePost API for sending email. You can find out more about MimePost at [https://mimepost.com](http://mimepost.com). For this sample, you can use the api key `special-key` to test the authorization filters.

OpenAPI spec version: 0.1.0
Contact: support@mimepost.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.18

=end

require 'spec_helper'
require 'json'

# Unit tests for Mimepost::WebhooksApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @instance = Mimepost::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@instance).to be_instance_of(Mimepost::WebhooksApi)
    end
  end

  # unit tests for webhooks_get
  # Get the list of all the webhooks
  # @param [Hash] opts the optional parameters
  # @return [ApiResponseAllWebhooks]
  describe 'webhooks_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_id_delete
  # Remove a single webhook
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ApiResponse]
  describe 'webhooks_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_id_get
  # Get the details of a single webhook
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ApiResponseSingleWebhooks]
  describe 'webhooks_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_id_put
  # Update the details of a single webhook
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Webhook1] :webhook 
  # @return [ApiResponseSingleWebhooks]
  describe 'webhooks_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for webhooks_post
  # Add single webhook
  # @param [Hash] opts the optional parameters
  # @option opts [Webhook] :webhook 
  # @return [ApiResponseWebhooks]
  describe 'webhooks_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
